Only check for auCDtect if operation was called
Also, fix issue with testing message operation prematurely
being unset if the operation was called after 'compress-notest'

diff --git a/redoflacs b/redoflacs
--- a/redoflacs
+++ b/redoflacs
@@ -1989,7 +1989,6 @@ __tidy_env () {
 			__compress_abort \
 			__print_compressing_flac \
 			__print_level_same_compression \
-			__print_testing_flac \
 			__log_compress_verify
 	fi
 
@@ -2472,48 +2471,50 @@ __check_missing_programs () {
 
 	# If auCDtect operation was specified, check
 	# if auCDtect is found/installed
-	aucdtect_exists="$(command -v auCDtect)"
+	if [[ "${aucdtect_flac}" == "true" ]] ; then
+		aucdtect_exists="$(command -v auCDtect)"
 
-	if [[ -z "${aucdtect_exists}" ]] ; then
-		# Check alternate spelling
-		aucdtect_exists="$(command -v aucdtect)"
-	fi
-
-	if [[ -z "${aucdtect_exists}" ]] ; then
-		# auCDtect can't be found, exit
-		{ __error "It appears auCDtect is not installed. Please verify you" ; __newline ;} >&2
-		{ __error "have this program installed and can be found in \$PATH" ; __newline 2 ;} >&2
-
-		{ __warn "You can install auCDtect by doing the following:" ; __newline ;} >&2
-		{ __warn "   wget --no-check-certificate -P /usr/local/bin/ https://raw.github.com/sirjaren/redoflacs/binaries/auCDtect.exe" ; __newline ;} >&2
-		{ __warn "   chmod +x /usr/local/bin/auCDtect.exe" ; __newline 2 ;} >&2
-
-		{ __warn "If you do _NOT_ have 'wget' installed in your Cygwin" ; __newline ;} >&2
-		{ __warn "environment, you can either install it via 'setup.exe'" ; __newline ;} >&2
-		{ __warn "(the Cygwin installer) and run the above commands or" ; __newline ;} >&2
-		{ __warn "you can download auCDtect using the link above and" ; __newline ;} >&2
-		{ __warn "move auCDtect to the correct location:" ; __newline ;} >&2
-		{ __warn "   mv /cygdrive/c/Users/Owner/Downloads/auCDtect.exe /usr/local/bin/" ; __newline ;} >&2
-		{ __warn "   chmod +x /usr/local/bin/auCDtect.exe" ; __newline ;} >&2
-
-		exit 1
-	else
-		# Check if auCDtect is executable and warn user if it isn't
-		if [[ ! -x "${aucdtect_exists}" ]] ; then
-			{ __error "It appears auCDtect is not executable.  In order to make" ; __newline ;} >&2
-			{ __error "auCDtect executable, run:" ; __newline ;} >&2
-			{ __error "chmod +x \"${aucdtect_exists}.exe\"" ; __newline ;} >&2
-
-			exit 1
+		if [[ -z "${aucdtect_exists}" ]] ; then
+			# Check alternate spelling
+			aucdtect_exists="$(command -v aucdtect)"
 		fi
 
-		# Set up auCDtect command
-		#
-		# Change all forward slashes to backslashes for Windows compatibility
-		aucdtect_command="${aucdtect_exists//\//\\}"
-		# Add Windows command (cmd) to run silently and terminate after
-		# completion
-		export aucdtect_command="cmd /C c:\\cygwin"${aucdtect_command}""
+		if [[ -z "${aucdtect_exists}" ]] ; then
+			# auCDtect can't be found, exit
+			{ __error "It appears auCDtect is not installed. Please verify you" ; __newline ;} >&2
+			{ __error "have this program installed and can be found in \$PATH" ; __newline 2 ;} >&2
+
+			{ __warn "You can install auCDtect by doing the following:" ; __newline ;} >&2
+			{ __warn "   wget --no-check-certificate -P /usr/local/bin/ https://raw.github.com/sirjaren/redoflacs/binaries/auCDtect.exe" ; __newline ;} >&2
+			{ __warn "   chmod +x /usr/local/bin/auCDtect.exe" ; __newline 2 ;} >&2
+
+			{ __warn "If you do _NOT_ have 'wget' installed in your Cygwin" ; __newline ;} >&2
+			{ __warn "environment, you can either install it via 'setup.exe'" ; __newline ;} >&2
+			{ __warn "(the Cygwin installer) and run the above commands or" ; __newline ;} >&2
+			{ __warn "you can download auCDtect using the link above and" ; __newline ;} >&2
+			{ __warn "move auCDtect to the correct location:" ; __newline ;} >&2
+			{ __warn "   mv /cygdrive/c/Users/Owner/Downloads/auCDtect.exe /usr/local/bin/" ; __newline ;} >&2
+			{ __warn "   chmod +x /usr/local/bin/auCDtect.exe" ; __newline ;} >&2
+
+			exit 1
+		else
+			# Check if auCDtect is executable and warn user if it isn't
+			if [[ ! -x "${aucdtect_exists}" ]] ; then
+				{ __error "It appears auCDtect is not executable.  In order to make" ; __newline ;} >&2
+				{ __error "auCDtect executable, run:" ; __newline ;} >&2
+				{ __error "chmod +x \"${aucdtect_exists}.exe\"" ; __newline ;} >&2
+
+				exit 1
+			fi
+
+			# Set up auCDtect command
+			#
+			# Change all forward slashes to backslashes for Windows compatibility
+			aucdtect_command="${aucdtect_exists//\//\\}"
+			# Add Windows command (cmd) to run silently and terminate after
+			# completion
+			export aucdtect_command="cmd /C c:\\cygwin"${aucdtect_command}""
+		fi
 	fi
 
 	# If "-A, --aucdtect-spectrogram" was called
